const Discord = require("discord.js")
exports.run = (bot, message, args) => {
	message.channel.sendMessage('lel').then(message => {
		message.edit('piu')
        message.edit('piu piu')
        message.edit('AISDHOÁSIGHDÍOSADÍSSIAOPGAISIPASHDPIASHDADPISAGHDIPSAGIDPOGSAIPODG')
        message.edit('pir piupiu')
        message.edit('tatatatata')
        message.edit('CABUWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW')
        message.edit('Stepmania>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Osu')
        message.edit('SOCOROOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO')
        message.edit('aptuapstupautpsautpsautpsaut')
        message.edit('askdsadkaskdkaskd')
        message.edit('piaspisatpsiatpiasptisaptisapi')
        message.edit('biiiiiiiiiiiiiiiibuibuibubiubiub')
        message.edit('Zerinha bot>>>>>>Mixy Bot')
        message.edit('LAELAELAUELAEULAEUALEUALEUAL')
        message.edit('UUUURURUARUAURUAURAURUAURAU')
        message.edit('**HELP ME**')
        message.edit('``HELP ME``')
        message.edit('__HELP ME__')
        message.edit('_HELP ME_')
        message.edit('HELP ME')
        message.edit('```HELP ME```')
        message.edit('piupiupuip')
        message.edit('GRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrr')
        message.edit('piupiupiu')
	})
}